jQuery ->
  # $('#document_entity_id').parent().hide()
  # $('#document_numero_credito').parent().hide()
  # $('#document_numero_escritura').parent().hide()
  # $('#document_fecha_escritura').parent().hide()
  # $('#document_nombre_notario').parent().hide()
  # $('#document_numero_notaria').parent().hide()
  # $('#document_nombre_acreditado').parent().hide()
  # $('#document_paterno_acreditado').parent().hide()
  # $('#document_materno_acreditado').parent().hide()
  # $('#document_nombre_coacreditado_1').parent().hide()
  # $('#document_paterno_coacreditado_1').parent().hide()
  # $('#document_materno_coacreditado_1').parent().hide()
  # $('#document_nombre_coacreditado_2').parent().hide()
  # $('#document_paterno_coacreditado_2').parent().hide()
  # $('#document_materno_coacreditado_2').parent().hide()
  # $('#document_nombre_coacreditado_3').parent().hide()
  # $('#document_paterno_coacreditado_3').parent().hide()
  # $('#document_materno_coacreditado_3').parent().hide()
  # $('#document_originator_id').parent().hide()
  # $('#document_cofi_id').parent().hide()
  # $('#document_calle').parent().hide()
  # $('#document_colonia').parent().hide()
  # $('#document_municipio').parent().hide()
  # $('#document_estado_id').parent().hide()
  # $('#document_jurisdiccion_id').parent().hide()
  # $('#document_folio_real_rpp').parent().hide()
  # $('#document_seccion_rpp').parent().hide()
  # $('#document_libro_rpp').parent().hide()
  # $('#document_volumen_rpp').parent().hide()
  # $('#document_partida_rpp').parent().hide()
  # $('#document_fecha_rpp').parent().hide()
  # $('#document_entidad_id').parent().hide()
  # $('#document_fecha_avaluo').parent().hide()
  # $('#document_monto_avaluo').parent().hide()
  # $('#document_nombre_archivo').parent().hide()
  $('#document_numero_demanda').parent().hide()
  $('#document_numero_expediente').parent().hide()
  $('#document_numero_juzgado').parent().hide()
  $('#document_ubicacion_juzgado').parent().hide()
  $('#document_fecha_auto_admisorio').parent().hide()

  $('#document_document_type_id').change ->
    if $('#document_document_type_id').val() == '1' || $('#document_document_type_id').val() == '2'
      $('#document_numero_credito').parent().show()
      $('#document_numero_escritura').parent().show()
      $('#document_fecha_escritura').parent().show()
      $('#document_nombre_notario').parent().show()
      $('#document_numero_notaria').parent().show()
      $('#document_entity_id').parent().show()
      $('#document_nombre_acreditado').parent().show()
      $('#document_paterno_acreditado').parent().show()
      $('#document_materno_acreditado').parent().show()
      $('#document_nombre_coacreditado_1').parent().show()
      $('#document_paterno_coacreditado_1').parent().show()
      $('#document_materno_coacreditado_1').parent().show()
      $('#document_nombre_coacreditado_2').parent().show()
      $('#document_paterno_coacreditado_2').parent().show()
      $('#document_materno_coacreditado_2').parent().show()
      $('#document_nombre_coacreditado_3').parent().show()
      $('#document_paterno_coacreditado_3').parent().show()
      $('#document_materno_coacreditado_3').parent().show()
      $('#document_originator_id').parent().show()
      $('#document_cofi_id').parent().show()
      $('#document_calle').parent().show()
      $('#document_colonia').parent().show()
      $('#document_municipio').parent().show()
      $('#document_estado_id').parent().show()
      $('#document_jurisdiccion_id').parent().show()
      $('#document_folio_real_rpp').parent().show()
      $('#document_seccion_rpp').parent().show()
      $('#document_libro_rpp').parent().show()
      $('#document_volumen_rpp').parent().show()
      $('#document_partida_rpp').parent().show()
      $('#document_fecha_rpp').parent().show()
      $('#document_entidad_id').parent().show()
      $('#document_fecha_avaluo').parent().show()
      $('#document_monto_avaluo').parent().show()
      $('#document_nombre_archivo').parent().show()
      $('#document_numero_demanda').parent().hide()
      $('#document_numero_expediente').parent().hide()
      $('#document_numero_juzgado').parent().hide()
      $('#document_ubicacion_juzgado').parent().hide()
      $('#document_fecha_auto_admisorio').parent().hide()
      $('#first_field').focus()
    else if $('#document_document_type_id').val() == '3'
      $('#document_entity_id').parent().hide()
      $('#document_numero_credito').parent().hide()
      $('#document_numero_escritura').parent().hide()
      $('#document_fecha_escritura').parent().hide()
      $('#document_nombre_notario').parent().hide()
      $('#document_numero_notaria').parent().hide()
      $('#document_nombre_acreditado').parent().hide()
      $('#document_paterno_acreditado').parent().hide()
      $('#document_materno_acreditado').parent().hide()
      $('#document_nombre_coacreditado_1').parent().hide()
      $('#document_paterno_coacreditado_1').parent().hide()
      $('#document_materno_coacreditado_1').parent().hide()
      $('#document_nombre_coacreditado_2').parent().hide()
      $('#document_paterno_coacreditado_2').parent().hide()
      $('#document_materno_coacreditado_2').parent().hide()
      $('#document_nombre_coacreditado_3').parent().hide()
      $('#document_paterno_coacreditado_3').parent().hide()
      $('#document_materno_coacreditado_3').parent().hide()
      $('#document_originator_id').parent().hide()
      $('#document_cofi_id').parent().hide()
      $('#document_calle').parent().hide()
      $('#document_colonia').parent().hide()
      $('#document_municipio').parent().hide()
      $('#document_estado_id').parent().hide()
      $('#document_jurisdiccion_id').parent().hide()
      $('#document_folio_real_rpp').parent().hide()
      $('#document_seccion_rpp').parent().hide()
      $('#document_libro_rpp').parent().hide()
      $('#document_volumen_rpp').parent().hide()
      $('#document_partida_rpp').parent().hide()
      $('#document_fecha_rpp').parent().hide()
      $('#document_entidad_id').parent().hide()
      $('#document_fecha_avaluo').parent().hide()
      $('#document_monto_avaluo').parent().hide()
      $('#document_nombre_archivo').parent().hide()
      $('#document_numero_demanda').parent().hide()
      $('#document_numero_expediente').parent().hide()
      $('#document_numero_juzgado').parent().hide()
      $('#document_ubicacion_juzgado').parent().hide()
      $('#document_fecha_auto_admisorio').parent().hide()
      $('#document_numero_demanda').parent().show()
      $('#document_numero_expediente').parent().show()
      $('#document_numero_juzgado').parent().show()
      $('#document_ubicacion_juzgado').parent().show()
      $('#document_fecha_auto_admisorio').parent().show()
      $('#numero_demanda').focus()
    else
      $('#document_entity_id').parent().hide()
      $('#document_numero_credito').parent().hide()
      $('#document_numero_escritura').parent().hide()
      $('#document_fecha_escritura').parent().hide()
      $('#document_nombre_notario').parent().hide()
      $('#document_numero_notaria').parent().hide()
      $('#document_nombre_acreditado').parent().hide()
      $('#document_paterno_acreditado').parent().hide()
      $('#document_materno_acreditado').parent().hide()
      $('#document_nombre_coacreditado_1').parent().hide()
      $('#document_paterno_coacreditado_1').parent().hide()
      $('#document_materno_coacreditado_1').parent().hide()
      $('#document_nombre_coacreditado_2').parent().hide()
      $('#document_paterno_coacreditado_2').parent().hide()
      $('#document_materno_coacreditado_2').parent().hide()
      $('#document_nombre_coacreditado_3').parent().hide()
      $('#document_paterno_coacreditado_3').parent().hide()
      $('#document_materno_coacreditado_3').parent().hide()
      $('#document_originator_id').parent().hide()
      $('#document_cofi_id').parent().hide()
      $('#document_calle').parent().hide()
      $('#document_colonia').parent().hide()
      $('#document_municipio').parent().hide()
      $('#document_estado_id').parent().hide()
      $('#document_jurisdiccion_id').parent().hide()
      $('#document_folio_real_rpp').parent().hide()
      $('#document_seccion_rpp').parent().hide()
      $('#document_libro_rpp').parent().hide()
      $('#document_volumen_rpp').parent().hide()
      $('#document_partida_rpp').parent().hide()
      $('#document_fecha_rpp').parent().hide()
      $('#document_entidad_id').parent().hide()
      $('#document_fecha_avaluo').parent().hide()
      $('#document_monto_avaluo').parent().hide()
      $('#document_nombre_archivo').parent().hide()
      $('#document_numero_demanda').parent().hide()
      $('#document_numero_expediente').parent().hide()
      $('#document_numero_juzgado').parent().hide()
      $('#document_ubicacion_juzgado').parent().hide()
      $('#document_fecha_auto_admisorio').parent().hide()

  $('#document_entity_name').autocomplete
    source: $('#document_entity_name').data('autocomplete-source')
  $('#document_originator_name').autocomplete
    source: $('#document_originator_name').data('autocomplete-source')
  $('#document_cofi_name').autocomplete
    source: $('#document_cofi_name').data('autocomplete-source')
  $('#document_estado_name').autocomplete
    source: $('#document_estado_name').data('autocomplete-source')
  $('#document_jurisdiccion_name').autocomplete
    source: $('#document_jurisdiccion_name').data('autocomplete-source')
  $('#document_entidad_name').autocomplete
    source: $('#document_entidad_name').data('autocomplete-source')

